name: rick_morty_flutter
description: Rick and Morty Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^7.0.1
  flex_color_scheme: ^7.1.2
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  injectable: ^1.5.3
  connectivity_plus: ^3.0.2
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  google_sign_in: ^5.4.2
  flutter_local_notifications: ^14.0.1
  permission_handler: ^10.1.0
  shimmer: ^2.0.0
  uuid: ^3.0.6
  intl: ^0.18.0
  graphql_flutter: ^5.1.2
  transparent_image: ^2.0.0
  like_button: ^2.0.5
  pedantic_mono: ^1.21.1
  url_strategy: ^0.2.0
  logging: ^1.0.2
  path: ^1.8.2
  provider: ^6.0.5

  clean_architecture:
    path: ./clean_architecture
  domain:
    path: ./domain
  data:
    path: ./data
  syncfusion_flutter_signaturepad: ^20.4.50


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  injectable_generator: any
  build_runner: any
  flutter_gen_runner: any
  bloc_test: ^9.1.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true
#  assets:
#    - assets/logos/
#    - assets/images/
#    - assets/icons/
