// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesmG-VOABs1sNKbzSYBarGzrBA64gc60',
    appId: '1:1080315079875:web:c1d58cb4d08c950e2c8676',
    messagingSenderId: '1080315079875',
    projectId: 'flutterpraxis',
    authDomain: 'flutterpraxis.firebaseapp.com',
    storageBucket: 'flutterpraxis.appspot.com',
    measurementId: 'G-YD3PRBQRYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPsKE8FTqFfLyHxSF5UR_xfYF0TzwbobE',
    appId: '1:1080315079875:android:50def698dd6274af2c8676',
    messagingSenderId: '1080315079875',
    projectId: 'flutterpraxis',
    storageBucket: 'flutterpraxis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD648P_AQMaTgT7Pbry-s_jAskmBpABBc0',
    appId: '1:1080315079875:ios:3398c66d2dc3c3722c8676',
    messagingSenderId: '1080315079875',
    projectId: 'flutterpraxis',
    storageBucket: 'flutterpraxis.appspot.com',
    iosClientId: '1080315079875-p3tudhenbh67jshudgrc5pqu63sovep8.apps.googleusercontent.com',
    iosBundleId: 'com.mutualmobile.praxisFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD648P_AQMaTgT7Pbry-s_jAskmBpABBc0',
    appId: '1:1080315079875:ios:3398c66d2dc3c3722c8676',
    messagingSenderId: '1080315079875',
    projectId: 'flutterpraxis',
    storageBucket: 'flutterpraxis.appspot.com',
    iosClientId: '1080315079875-p3tudhenbh67jshudgrc5pqu63sovep8.apps.googleusercontent.com',
    iosBundleId: 'com.mutualmobile.praxisFlutter',
  );
}
